version: "3.9"

services:
  mimosanpm-agent:
    image: ghcr.io/successbyfailure/mimosanpm-agent:latest
    build: .
    env_file: .env
    restart: unless-stopped
    volumes:
      - ./state:/state
      - /ruta/a/logs/npm:/data/logs:ro
    networks:
      - npm_stack

networks:
  npm_stack:
    external: true
